
from .cut_into_triangles import cut_image_into_triangles
from .cut_into_rectangles import cut_image_into_rectangles
from .shuffle_peases import shuffle_peases, shuffle_triangle_peases, shuffle_rectangle_peases
from .merge_from_rectangles import merge_from_rectangles
from .merge_from_triangles import merge_from_triangles

